FROM cyberdojofoundation/gcc:ee0bdcd
LABEL maintainer=jon@jaggersoft.com

ENV DEBIAN_FRONTEND=noninteractive

COPY install.sh .
RUN ./install.sh && rm ./install.sh
COPY red_amber_green.rb /usr/local/bin
